### DISCUSSION TITLE
Open Graph Image - Is it possible to set this to a field?

### DISCUSSION THREAD

**Discussion by sunscreem** [aerni/statamic-advanced-seo#87] [Ideas]
I'm missing something obvious I'm sure but I'm trying to work out how to set Advance SEO to use a field on an entry as the OG image?

**Comment by aerni** [comment]
You can't. 

As a workaround, you could activate the social images generator and use the image field you want as the OG image in the social images's Antlers template.

**Comment by sunscreem** [comment]
Thanks @aerni - I'll give this a go. Can I pop this in as a feature request please?

**Comment by aerni** [comment]
Sure. But I'm not planning to implement it any time soon as it would involve a major refactor.

Another workaround that just came to mind: If you don't want the user to be able to specifically change the OG Image but instead always want to inherit it from another field in your blueprint, you could remove the OG image field from the SEO blueprint and use a computed field instead. More about this approach here: https://advanced-seo.michaelaerni.ch/usage/customizing-fields

**Reply by sunscreem** [reply]
Hey @aerni Thank you for this idea. Apologies for the slow reply. I've been having a look into this. 

The computed field would need to return the same type of field as Advanced SEO would have - can you confirm what type that is? I'm still learning my way around the code of statamic (and the plug in).

**Reply by sunscreem** [reply]
Hey again @aerni I've tried this. Almost 100%.. just one query. I've lost the SEO tab on the entries now. I note in the docs you warn about this, but wondering if you can check over the code I've added and see if there's a way to continue to show the SEO tab?

In my `app/Providers/ControlPanelServiceProvider.php:`
```php

    public function boot()
    {
        Collection::computed('news_and_views','seo_og_image',function($entry,$value){
            return $entry->get('summary_image');
        });
    }
```

in my `resources/blueprints/collections/news_and_views/news_and_views.yaml:`

```yaml

          -
            handle: seo_og_image
            field:
              type: assets
              display: 'Open Graph Image'
              visibility: computed
              instructions_position: above
              listable: hidden
              max_files: 1
              mode: list
              container: spaces
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              hide_display: false
              
```

Like I said, this appears to be working well - just that missing SEO tab on the entry thats a problem for me just now.
